FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# ติดตั้ง Python, pip และ nvme-cli (สำหรับอ่าน SMART)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip nvme-cli \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["python3","-m","uvicorn","main:app","--host","0.0.0.0","--port","8000"]
